### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by sinakiaei** [tarcadius/LDAR_Sim#40]
I ran the code for the first time as instructed. It took me over 18 hours to finish the first run to get the sensitivity for OGI and truck. I am wondering if this is normal?

**Comment by tarcadius** [comment]
Hi Sina - no this is very abnormal! It should take around 5 minutes to run the model. Sensitivity analysis can take much longer, but we recommend against using the old version of this because it is hard coded to specific applications that are defunct in the new version. V2 of LDAR-Sim has a much better sensitivity analysis.
